
on:
  push:
    branches:
      - main
    paths:
    - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X deployment
    steps:
#    仓库检查
    - name: Checkout repository
      uses: actions/checkout@v2

#    生成仓库tag
    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%Y_%m_%d_%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
#构建并推送镜像到指定dockerhub仓库
    - name: Build an action server
      uses: RasaHQ/rasa-action-server-gha@main
      with:
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_image_name: ${{ secrets.DOCKER_HUB_LOGIN }}/action_server
        # More details on how to use GitHub secrets:
        # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

        # More details about github context:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        docker_image_tag: ${{ steps.prep.outputs.BUILD_ID }}
        requirements_file: 'actions/requirements.txt'

